### PR TITLE
Unit tests for Core Contract

### PR DESCRIPTION
**Pull request by 0xNilesh**
Unit tests for:
1> UpdateChannelMeta
2> Contract Pausability
3> Timebound Channel
4> Incentivized Chat Requests

Solves https://github.com/ethereum-push-notification-service/push-smart-contracts/issues/230

### CODE REVIEW

**Comment by 0xNilesh** [comment]
Note: Tests are included only for UpdateChannelMeta and Pausability as of now, that's why draft PR

**Comment by zaryab2000** [comment]
Sure, starting the review for the above-mentioned test suites for now @0xNilesh

**Comment by 0xNilesh** [comment]
Pushed test cases for timeBound channel functionality as well @zaryab2000

**Comment by 0xNilesh** [comment]
Pushed test cases for incentivizedChatRequest feature as well @zaryab2000 
It's ready for review now

**Comment by zaryab2000** [comment]
The review of this PR has now completed and mentioned below are a few comments around the same:

1. The use of **BasePushChannelStateCycle** is redundant and therefore should be removed. 
***Note: Its better to have fewer effective BASE test files and only create when abosluetly necessary. This helps in maintaining the test structure adequately in the long run***

- _The inclusion of **BasePushCoreTest is a good call though🦾 ._**

2. **Regarding updateChannelMeta()**
    a. A few minor notes on The TREE file of updateChannelMeta() function:
    *  Tree file is not very specific in the VALID scenarios (*scenarios where function would be actually be executed without any reverts*)
        *  For instance, this part:
        > when amount passed is accurate
                    ├── it should update the channel successfully
                    ├── it should update variables correctly
                    └── fees should increase linearly for every update
        * We should specify the exact variables that are supposed to be updated
        * And, how exactly should the counter be updated,
        * And, which event exactly should be emitted, etc.
    *  The file includes limited information about the zeroAddress scenario in terms of updateChannelMeta() function.
        *  For instances, this line -   ` ── when caller is not channel owner (if caller is pushChannelAdmin, then channel should be zero address)` could have branches of its own (*instead of using brackets*)
        * **Note:** *The aim of having tree files is to include every possible scenarios (branches) of a given function, irrespective of whether the logic actually passes/failes from contract side. These branches are the converted to tests, not the other way round.*
    * Use of abstract terms like alright should be avoided. For instace, alright -> valid.
    
    b. Since changing the error code *UnauthorisedCaller* to *InvalidChannel* requires some changes in the function code which raises the gas consumption (as per the internal gas reviews), we will not include this minor change for now.
    
4. **Unused Imports**: Found a couple of instances of unused imports in some test files. Those have been mentioned below:
* Line 4, in updateChannelMeta.t.sol
* Line 4 of /contractPausability.t.sol
* Line 6, BasePushIncentivizedChatRequest.t.sol
* Line 4, createIncentivizedChatRequest.t.sol, handleIncentivizedChatData.t.sol, claimIncentives

---

**Note**
1. Since there were additional conflicts in this PR as the new structure was pushed before this, a new PR was created to include these tests as per the new structure.
2. All these changes have been addresses already in this PR 👉 #251 . (except the TREE file suggestions). Feel free to review. @0xNilesh @Zartaj0

**Comment by zaryab2000** [comment]
Changes have already been merged and closed with PR #251 . Therefore, closing this PR.

**Pull request closed without merging**
