### PR TITLE
231 define adequate interfaces

### PR DESCRIPTION
**Pull request by Zartaj0**
This PR includes updated interfaces for Core and Comm with all the public/external functions mentioned .

Solves https://github.com/ethereum-push-notification-service/push-smart-contracts/issues/231 and #243

### CODE REVIEW

**Review by Zartaj0 — COMMENTED** [review]
LGTM

**Comment by Zartaj0** [comment]
@zaryab2000 we can merge this I think, if there are no more changes required.

**Review by Zartaj0 — COMMENTED** [review]
LGTM, need to resolve the conflicts.

**Review by Zartaj0 — COMMENTED** [review]
All good @zaryab2000

**Review by zaryab2000 — APPROVED** [review]

**Pull request merged**
